use std::fmt::Write;
use std::fs;
use std::path::Path;
use std::sync::Arc;
use fury_core::schema::registry::{FieldType, ModelSchema};

use crate::errors::CliError;

/// Iterates over validated schemas and writes the corresponding TypeScript classes to disk.
pub fn generate_all(schemas: &[Arc<ModelSchema>], dst_dir: &Path) -> Result<(), CliError> {
    if !dst_dir.exists() {
        fs::create_dir_all(dst_dir).map_err(|e| CliError::Io {
            path: dst_dir.to_path_buf(),
            source: e,
        })?;
    }

    for schema in schemas {
        let ts_code = generate_class_string(schema);
        let file_name = format!("{}.ts", schema.name().to_lowercase());
        let file_path = dst_dir.join(&file_name);

        fs::write(&file_path, ts_code).map_err(|e| CliError::Io {
            path: file_path,
            source: e,
        })?;
    }

    Ok(())
}

/// Constructs the TypeScript class payload with getters and setters mapped to WASM boundary calls.
fn generate_class_string(schema: &ModelSchema) -> String {
    let mut code = String::with_capacity(2048);
    let name = schema.name();

    writeln!(code, "// AUTO-GENERATED BY FURY CLI. DO NOT EDIT.").unwrap();
    writeln!(code, "import {{ WasmRecord }} from '@fury/wasm-core';\n").unwrap();

    writeln!(code, "export class {} {{", name).unwrap();
    writeln!(code, "    private readonly _internal: WasmRecord;").unwrap();

    writeln!(code, "\n    constructor(buffer?: Uint8Array) {{").unwrap();
    writeln!(code, "        this._internal = new WasmRecord('{}', buffer);", name).unwrap();
    writeln!(code, "    }}").unwrap();

    for field in schema.fields() {
        let field_name = field.name();

        match field.field_type() {
            FieldType::Int32 | FieldType::Int64 | FieldType::Float64 => {
                writeln!(code, "\n    public get {}(): number {{ return this._internal.getNumber('{}'); }}", field_name, field_name).unwrap();
                writeln!(code, "    public set {}(val: number) {{ this._internal.setNumber('{}', val); }}", field_name, field_name).unwrap();
            }
            FieldType::Bool => {
                writeln!(code, "\n    public get {}(): boolean {{ return this._internal.getBool('{}'); }}", field_name, field_name).unwrap();
                writeln!(code, "    public set {}(val: boolean) {{ this._internal.setBool('{}', val); }}", field_name, field_name).unwrap();
            }
            FieldType::String => {
                writeln!(code, "\n    public get {}(): string {{ return this._internal.getString('{}'); }}", field_name, field_name).unwrap();
                writeln!(code, "    public set {}(val: string) {{ this._internal.setString('{}', val); }}", field_name, field_name).unwrap();
            }
            FieldType::Bytes => {
                writeln!(code, "\n    public get {}(): Uint8Array {{ return this._internal.getBytesView('{}'); }}", field_name, field_name).unwrap();
                writeln!(code, "    public set {}(val: Uint8Array) {{ this._internal.setBytes('{}', val); }}", field_name, field_name).unwrap();
            }
            FieldType::DateTime | FieldType::Date => {
                writeln!(code, "\n    public get {}(): Date {{ return this._internal.getDate('{}'); }}", field_name, field_name).unwrap();
                writeln!(code, "    public set {}(val: Date) {{ this._internal.setDate('{}', val); }}", field_name, field_name).unwrap();
            }
            _ => {
                writeln!(code, "\n    // TODO: Field '{}' of type {:?} requires custom mapping", field_name, field.field_type()).unwrap();
            }
        }
    }

    writeln!(code, "\n    public toBytes(): Uint8Array {{ return this._internal.toBytes(); }}").unwrap();
    writeln!(code, "}}").unwrap();

    code
}